# Generated by Django 3.0.2 on 2021-03-29 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satart_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('discription', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Recruiter')),
            ],
        ),
    ]
